### ISSUE TITLE
GetLatestTick with oneMin interval only updates every 2 minutes

### ISSUE THREAD

**Issue by shabbyrobe** [thebotguys/golang-bittrex-api#22]
When I call `GetTicks("BTC-ETH", "oneMin")`, I get timestamps that only change every two minutes! I'm guessing this isn't a problem with this API per se, but perhaps `oneMin` shouldn't be supported if you can't actually get one minute periods from the underlying API?

```
{"success":true,"message":"","result":[{"O":0.07610779,"H":0.07611000,"L":0.07600001,"C":0.07600001,"V":29.27156163,"T":"2017-08-26T08:06:00","BV":2.22756684}]}
{"success":true,"message":"","result":[{"O":0.07610999,"H":0.07634000,"L":0.07610999,"C":0.07610999,"V":11.24839887,"T":"2017-08-26T08:08:00","BV":0.85615189}]}
```

**Comment by saniales** [comment]
I think this is a bug related to cloudflare as a bittrex DDoS protection. In fact if you print the header sometimes cloudflare will set `max-age`

**Comment by shabbyrobe** [comment]
Awesome, thanks!

**Comment by saniales** [comment]
for now just try to get 1 min info like every min and 5 seconds

**Comment by shabbyrobe** [comment]
Unfortunately, it doesn't work - it's definitely at their end. I've got another experiment on the go, will post here if it works.

```
$ while true; do curl -s 'https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-ETH&tickInterval=oneMin'; echo; sleep 5; done
```

The only times I get out of that (`jq '.result[].T' | sort -u`) are:

```
"2017-08-26T10:21:00"
"2017-08-26T10:23:00"
"2017-08-26T10:25:00"
```

For my use case, I don't necessarily need it every minute, I just need that missing minute's candle. Will update if I find anything. I guess I was just raising it because until the underlying problem is fixed at Bittrex's end, any API that exposes the oneMin interval is making promises it can't keep, and which might not be immediately obvious to a user.

**Comment by shabbyrobe** [comment]
Darn, didn't work. I tried to see if I could call GetTicks instead of GetLatestTick but close the response body reader after reading 2k instead of 2mb, then parse the incomplete JSON manually. Didn't bother to make sure they come out newest-to-oldest first, of course they don't! 😳

**Comment by saniales** [comment]
LOL for now I will remove oneMin option as part of the roadMap (Allow `fiveMin` `thirtyMin` and hour/day intervals)

**Comment by shabbyrobe** [comment]
Actually now that I think of it, GetTicks with oneMin works just fine, it's just GetLatestTick. What's the best way to protect people from making the same mistake I made without reducing the utility of the library? GetLatestTick at a two minute update interval might actually be useful, it's just at the moment because the Bittrex API is broken for just that one case, you don't quite get what you ask for when you call GetLatestTick with oneMin.

**Comment by saniales** [comment]
hopefully Bittrex team will read this and fix the api too. This issue will remain open and will ne signaled to them :)

**Comment by saniales** [comment]
anw for now GetLatestTick will be removed until they fixed it

**Comment by saniales** [comment]
I signaled this to bittrex team and they did not answer, so I am closing this issue, waiting for their devs to change the API on their end. Thank you :)

**Comment by mozhunt** [comment]
Guys, can you help me ? How can i get the previous data of GetLatestTick in Bittrex ? 
Example: 
https://bittrex.com/Api/v2.0/pub/market/GetLatestTick?marketName=BTC-LTC&tickInterval=fiveMin&timestamp=1514734200
write
{"success":true,"message":"","result":[{"O":0.01687427,"H":0.01697220,"L":0.01682000,"C":0.01694900,"V":571.53639338,"T":"2018-01-01T11:35:00","BV":9.68828861}]}

but it's data from 11:35 till 11:40 and it's changes , thats why it's incorrect. 
Correct will be after thes perios closed - in 11:41. 
But in this time GetLatestTick will be show the data since 11:40 till 11:45 . 

If i use GetTicks , i get all 4760 strings of data, but need one previous before the last.
What can i do? What i should use ?
Sorry for my english :)

**Comment by saniales** [comment]
@mozhunt you have to use GetTicks only

**Comment by mozhunt** [comment]
But in GetTicks i get a lot of useless data ..

**Comment by saniales** [comment]
There is no other way, contact bittrex team if you think it's a wrong approach
