### ISSUE TITLE
acquiring the __RequestVerificationToken

### ISSUE THREAD

**Issue by meetri** [thebotguys/golang-bittrex-api#23]
how do we go about getting this request verification token ?

in v1.1 we would send the apikey as part of the query. I assume there is a step to get this token using the apikey.  Does anyone have details on this?

thanks!

**Comment by saniales** [comment]
i just saw there are different endpoints for apis. something like /api/feature instead of pub or auth

**Comment by Ornolfr** [comment]
Have the same question, how do we get it?

**Comment by saniales** [comment]
https://stackoverflow.com/questions/14051456/whats-the-use-of-the-requestverificationtoken

**Comment by Ornolfr** [comment]
@saniales how is your answer relevant to Bittrex API?

**Comment by Ornolfr** [comment]
For instance, in API v1.1 we use API key as query parameter and sign the request link with secret key using HMAC512 algo. How do we do with the new __RequestVerificationToken ?

**Comment by saniales** [comment]
@Ornolfr this is still an open issue, since Private API are not yet implemented in v2 for this wrapper

**Comment by saniales** [comment]
Private API will use key pair, not this verification token, I am closing this issue due to this reason.
