### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by CryptoDogs** [thebotguys/golang-bittrex-api#24]
in README.md,
in the private API example,
I read

```
 auth := bittrex.Auth{
     PublicKey: "YOUR-PUBLIC-KEY",
     SecretKey: "YOUR-SECRET-KEY",
 }
```
------------------------------------------------------------------------
It should be
```
 auth := bittrex.Auth{
     PublicKey: "YOUR-PUBLIC-KEY",
     PrivateKey: "YOUR-SECRET-KEY",
 }
```

**Comment by saniales** [comment]
why? SecretKey and PrivateKey are always used as similar keywords.
anw i will use SecretKey as PrivateKey

**Comment by saniales** [comment]
No answer, issue closed since it's minor
