### ISSUE TITLE
Where information about API is taken from?

### ISSUE THREAD

**Issue by dominikduda** [thebotguys/golang-bittrex-api#25]
Is there any official DOC on the API v2.0?

Or did you just reverse-engineer it?
If is there at least information that it won't change soon?

Thanks in advance.

**Comment by saniales** [comment]
I reverse engineered it.
Wanna help? fork this repo and open a PR :)

**Comment by firhatnawfanh** [comment]
hi saniales, can you give hint/ general instruction on how to reverse engineer bittrex api then?

i only found the ticks by inspecting from firefox developer console, can't find anything else

**Comment by saniales** [comment]
There is the section in the wiki, you can search there :)
