### ISSUE TITLE
go get github.com/thebotguys/golang-bittrex-api does not work

### ISSUE THREAD

**Issue by pavelz** [thebotguys/golang-bittrex-api#33]
go get github.com/thebotguys/golang-bittrex-api

can't load package: package github.com/thebotguys/golang-bittrex-api: no Go files in /Users/pavel/.gopath/src/github.com/thebotguys/golang-bittrex-api

**Comment by valuka** [comment]
Use go get github.com/thebotguys/golang-bittrex-api/bittrex and it will work.
