### ISSUE TITLE
BuyLimit \ TradeBuy

### ISSUE THREAD

**Issue by trojanhost** [thebotguys/golang-bittrex-api#4]
i write windows application for Bittrex crypto trading (Delphi).

i want use method:
https://bittrex.com/api/v2.0/auth/market/TradeBuy

but i dont known how take __RequestVerificationToken: "HIDDEN_FOR_PRIVACY"

the http.post() return HTTP 500 (internal Server Error).

i wrote to bittrex support 3 messages, but Did not get an answer.

**Comment by saniales** [comment]
marked as duplicate
