### ISSUE TITLE
BuyLimit \ TradeBuy

### ISSUE THREAD

**Issue by trojanhost** [thebotguys/golang-bittrex-api#5]
i use bittrex API.
how use method BuyLimit with "ConditionType" and "Target" parameters?

this sample dont work? :

https://bittrex.com/api/v2.0/auth/market/tradebuy?&nonce=1502481723&MarketName=BTC-BCC&OrderType=LIMIT&Quantity=0.0005
&Rate=0.10271362101&TimeInEffect=IMMEDIATE_OR_CANCEL&ConditionType=GREATER_THAN&Target=0.10271362101

**Comment by saniales** [comment]
you need to authenticate, I think API KEYS AND SECRETS come into place at this point, I am figuring out how

**Comment by trojanhost** [comment]
i tested and analized this method from Google Chrome:

Request URL:https://bittrex.com/api/v2.0/auth/market/TradeBuy
Referrer Policy:no-referrer-when-downgrade
Request Headers
Provisional headers are shown
Accept:application/json, text/javascript, */*; q=0.01
Content-Type:application/x-www-form-urlencoded
Origin:https://bittrex.com
Referer:https://bittrex.com/Market/Index?MarketName=BTC-SC
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
MarketName:BTC-SC
OrderType:LIMIT
Quantity:21342342424.00000000
Rate:234234321432424.00000000
TimeInEffect:IMMEDIATE_OR_CANCEL
ConditionType:GREATER_THAN
Target:234234214324
__RequestVerificationToken:*****************************************************

! not have cookies (with __RequestVerificationToken) and API-Keys in query !



the __RequestVerificationToken is [ValidateAntiForgeryToken] (ASP NET attribute)

the __RequestVerificationToken have as hidden html tag in current page (sample: https://bittrex.com/Market/Index?MarketName=BTC-SC)

<input name="__RequestVerificationToken" type="hidden" value="*****">

i copy (for test) this html tag value to my project, but bittrex return
HTML 500 internal error

**Comment by saniales** [comment]
I think every call with __RequestVerificationToken is browser only, we still need a way to figure out how API_KEYS come into play

**Comment by trojanhost** [comment]
good day, Alessandro!

I'm also looking for a way to solve this TradeBuy with API_KEYs
(  The method "Buy with conditions" is very important for implementing the strategy of my trading robot. I successfully trade a robot on Forex and I also want to trade on Bittrex.  )

Sorry for my "google-translate" english :)
Can you report about this problem with bittrex support? 
Maybe in bittrex support did not understand me?
- I did not get any response from bittrex support (

**Comment by saniales** [comment]
since API v2 is not public yet, they do not answer. I tried too :(
